project:
  type: book
  output-dir: docs

book:
  title: "The moiraine R package user manual"
  author: "Olivia Angelin-Bonnet"
  search: true
  repo-url: https://github.com/PlantandFoodResearch/moiraine
  sharing: [twitter]
  chapters:
    - index.qmd
    - example_dataset.qmd
    - part: "Data preparation"
      chapters:
      - data_import.qmd
      - inspecting_multidataset.qmd
      - modifying_multidataset.qmd
      - preprocessing.qmd
      - prefiltering.qmd
    - part: "Unsupervised integration"
      chapters:
      - spls.qmd
      - so2pls.qmd
      - mofa.qmd
    - part: "Supervised integration"
      chapters:
      - diablo.qmd
    - part: "Results interpretation"
      chapters:
      - interpretation.qmd
      - evaluation.qmd
      - comparison.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true

