project:
  type: book
  output-dir: docs

book:
  title: "The `moiraine` R package user manual"
  author: "Olivia Angelin-Bonnet"
  search: true
  site-url: https://plant-food-research-open.github.io/moiraine-manual/
  sharing: [twitter]
  favicon: "images/logo.png"
  sidebar:
    tools:
      - icon: github
        menu:
          - text: Manual source code
            url: https://github.com/Plant-Food-Research-Open/moiraine-manual
          - text: Package source code
            url: https://github.com/Plant-Food-Research-Open/moiraine
  chapters:
    - index.qmd
    - overview.qmd
    - example_dataset.qmd
    - part: "Data preparation"
      chapters:
      - data_import.qmd
      - inspecting_multidataset.qmd
      - modifying_multidataset.qmd
      - preprocessing.qmd
      - prefiltering.qmd
    - part: "Unsupervised integration"
      chapters:
      - spls.qmd
      - so2pls.qmd
      - mofa.qmd
    - part: "Supervised integration"
      chapters:
      - diablo.qmd
    - part: "Results interpretation"
      chapters:
      - interpretation.qmd
      - evaluation.qmd
      - comparison.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true

